In [1]:
import numpy as np

# How to Create an Array

## Create arrays from lists

In [2]:
a = np.array([1,2,3])
print(a)
print(f'Dimension: {a.ndim}')

[1 2 3]
Dimension: 1


In [3]:
b = np.array([[1.5,2,3], [4,5,6]],dtype=float)
print(b)
print(f'Dimension: {b.ndim}')

[[1.5 2.  3. ]
 [4.  5.  6. ]]
Dimension: 2


## Create arrays with 0's, 1's, and a random number

In [4]:
np.zeros([2,3]) #Create an array of zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [5]:
 np.ones(4)

array([1., 1., 1., 1.])

In [6]:
np.full([3,3], 8)

array([[8, 8, 8],
       [8, 8, 8],
       [8, 8, 8]])

## Create arrays with a range of elements

In [7]:
np.arange(5,30,5)

array([ 5, 10, 15, 20, 25])

# Basic Operations

In [8]:
a = np.array([2,3,4])
b = np.array([[3,4,5], [6,7,8]])

## Addition

In [9]:
print(a+b)
print(np.add(b,a))

[[ 5  7  9]
 [ 8 10 12]]
[[ 5  7  9]
 [ 8 10 12]]


## Subtraction

In [10]:
print(a-b)
print(np.subtract(a,b))

[[-1 -1 -1]
 [-4 -4 -4]]
[[-1 -1 -1]
 [-4 -4 -4]]


## Multiplication

In [11]:
print(a*b)
print(np.multiply(a,b))

[[ 6 12 20]
 [12 21 32]]
[[ 6 12 20]
 [12 21 32]]


## Division

In [12]:
print(b/a)
print(np.divide(b,a))

[[1.5        1.33333333 1.25      ]
 [3.         2.33333333 2.        ]]
[[1.5        1.33333333 1.25      ]
 [3.         2.33333333 2.        ]]


In [13]:
print(a.sum())
print(a.min())
print(b.max(axis= 0))
print(b.cumsum(axis= 1)) #Cumulative sum 
print(a.mean())
print(np.std(b)) #Standard deviation

9
2
[6 7 8]
[[ 3  7 12]
 [ 6 13 21]]
3.0
1.707825127659933


# Array Manipulation

## Transposing and Reshaping a matrix

In [14]:
c = np.array([4,5,6,7,8,9])
print(c)

[4 5 6 7 8 9]


In [15]:
print(c.reshape(2,3))

[[4 5 6]
 [7 8 9]]


In [16]:
print(c.reshape(3,2))

[[4 5]
 [6 7]
 [8 9]]


In [17]:
d = c.reshape(3,2)
print(d.T)

[[4 6 8]
 [5 7 9]]


## Indexing and Slicing

In [18]:
# Subsetting:
b = np.array([[3,4,5], [6,7,8]])
print(b)
print(b[1,2])

[[3 4 5]
 [6 7 8]]
8


In [19]:
# Slicing:
a = np.arange(5,20,2)
print(a)
print(a[0:2])

[ 5  7  9 11 13 15 17 19]
[5 7]


In [20]:
# Boolean Indexing:
a[a<10]

array([5, 7, 9])

## Concatenate arrays

In [21]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

In [22]:
np.concatenate((a, b)) # rows
# np.concatenate((a, b), axis=0) # rows

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [23]:
np.concatenate((a, b), axis=1) # columns

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])